### ISSUE TITLE
The manufacturing process of datasets.

### ISSUE THREAD

**Issue by robot1lyj** [zxzm-zak/VLM#3]
Thank you for your work. I'd like to ask about the production process of datasets. Will it be released? Or could you provide me with some reference materials? Thanks a lot.

**Comment by zxzm-zak** [comment]
hi! Sorry for the late reply. The dataset was refined after many rounds of dialogue between me and chatgpt, which is the refinement of memory. I tested which feedback can help chatgpt output a more accurate plan. These feedbacks are then refined and summarized into dataset. You can take a look at the memory.json published in my data set (I only published part of the memory), follow this example to generate more memories and then refine it into a dataset.

**Comment by robot1lyj** [comment]
Thank you for your reply! I have a 4090 now. Can I perform fine-tuning? I also want to ask if the datasets on Google are all-inclusive?

**Comment by zxzm-zak** [comment]
Yes, 4090 is enough for llava-7b. And the data set I released already contains all the tasks, you can try it directly.
